{% set name = "datasets" %}
{% set version = "1.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f3c15323dd5358184cc73e5b11e90e1e67f30c680dfc685d04903297cc09432

build:
  noarch: python
  number: 1
  entry_points:
    - datasets-cli=datasets.commands.datasets_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp
    - dataclasses
    - dill
    - fsspec >=2021.05.0
    - huggingface_hub >=0.0.14,<0.1.0
    - importlib-metadata
    - multiprocess
    - numpy >=1.17
    - packaging
    - pandas
    - pyarrow >=1.0.0,!=4.0.0
    - python
    - requests >=2.19.0
    - tqdm >=4.62.1
    - python-xxhash

test:
  imports:
    - datasets
    - datasets.commands
    - datasets.utils
  commands:
    - pip check
    - datasets-cli --help
  requires:
    - pip

about:
  home: https://github.com/huggingface/datasets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: HuggingFace/Datasets is an open library of NLP datasets.
  doc_url: https://huggingface.co/docs/datasets/
  dev_url: https://github.com/huggingface/datasets

extra:
  recipe-maintainers:
    - oblute
    - Tata17
    - thewchan
    - mxr-conda
    - wietsedv
